// <auto-generated />
using System;
using FinReportBuilder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinReportBuilder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231009033455_InitialCrate")]
    partial class InitialCrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("FinReportBuilder.Models.Reports.FinancialReportYearEnd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ABN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BasisOfReport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmPartnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasABN")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPropertyPlantEquipment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyPlantEquipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyPlantEquipmentDepreciation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportGeneratedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearEndedStatement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FinancialReportYearEnds");
                });
#pragma warning restore 612, 618
        }
    }
}
